### ISSUE TITLE
"Det finns ingen meny för v18"

### ISSUE THREAD

**Issue by ctankep23** [Kaptensanders/skolmat-card#1]
Great addition to my family's dashboard! However..
While the rss feed (week) seems to work fine, and a normal entity card gets populated (with only todays menu), the skolmat-card  doesn't pick up anything from the rss-feed. It just says "Det finns ingen meny för v18"

<img width="341" alt="Screenshot 2022-05-06 at 21 33 51" src="https://user-images.githubusercontent.com/63706053/167205614-9182cc9d-3890-498c-8a2a-7aef442f5131.png">

**Comment by Kaptensanders** [comment]
Hey! Would you please drop me the link to your rss feed and also if you could paste a screenshot of the attributes for the sensor, from the dev tools page. 
There may also be a error output in the browser dev tool console that could be useful.

**Comment by yabbah** [comment]
Same problem here. From dev console

skolmat-card.js?hacstag=457767453110:194 TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at SkolmatCard.getWeekCalendar (skolmat-card.js?hacstag=457767453110:165:19)
    at SkolmatCard.renderWeek (skolmat-card.js?hacstag=457767453110:180:29)
    at SkolmatCard.render (skolmat-card.js?hacstag=457767453110:100:73)
    at SkolmatCard.update (styles.ts:368:1)
    at SkolmatCard.performUpdate (styles.ts:368:1)
    at SkolmatCard.scheduleUpdate (styles.ts:368:1)
    at SkolmatCard._$EC (styles.ts:368:1)

link to the rss: https://skolmaten.se/wendela-hellmanskolan/rss/weeks/

Sensor status in dev tools: 
<img width="852" alt="image" src="https://user-images.githubusercontent.com/13518966/167301681-6361d489-26b8-45a5-af0f-886567b92347.png">

**Comment by Kaptensanders** [comment]
> 

Yours works fine with my installation,
![image](https://user-images.githubusercontent.com/24979195/167361432-71d52a3e-b9b4-4aec-8be0-e4b8dcced400.png)

Seems your sensor does not get populated properly,  not the same issue as for @ctankep23. Check the your HA logs. Here's my config:

```
  - platform: skolmat
    name: Wendela Hellmanskolan
    rss: "https://skolmaten.se/wendela-hellmanskolan/rss/weeks/"
    format: first
```

**Comment by ctankep23** [comment]
Sure! I do get todays menu, but not the weekly menu.

```
skolmat-card.js?hacstag=457767453110:194 TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at SkolmatCard.getWeekCalendar (skolmat-card.js?hacstag=457767453110:165:19)
    at SkolmatCard.renderWeek (skolmat-card.js?hacstag=457767453110:180:29)
    at SkolmatCard.render (skolmat-card.js?hacstag=457767453110:100:73)
    at SkolmatCard.update (styles.ts:368:1)
    at SkolmatCard.performUpdate (styles.ts:368:1)
    at SkolmatCard.scheduleUpdate (styles.ts:368:1)
    at SkolmatCard._$EC (styles.ts:368:1)
renderWeek @ skolmat-card.js?hacstag=457767453110:194
```
<img width="776" alt="Screenshot 2022-05-09 at 11 33 12" src="https://user-images.githubusercontent.com/63706053/167382589-21241782-aaeb-44c4-aad0-b7453adfea55.png">

https://skolmaten.se/gustav-vasa/rss/weeks

<img width="819" alt="Screenshot 2022-05-09 at 11 36 34" src="https://user-images.githubusercontent.com/63706053/167383220-322c9981-266b-43ff-b934-358f8f0cc48b.png">

**Comment by yabbah** [comment]
Same here, I just get todays menu (half of it), not the rest of the week. 

Here's a screenshot from skolmaten.se's webpage:

![image](https://user-images.githubusercontent.com/13518966/167429010-816ea548-4624-4fa5-b9c9-80a455ab885d.png)

Here is my sensor in HA, only the veg alternative is populate. No errors in the logs.

![image](https://user-images.githubusercontent.com/13518966/167429118-d5431025-32dd-4ec6-b02a-2b7be35a0ab3.png)

**Comment by Kaptensanders** [comment]
@jsk-sct , yes for sure, seems like it is bailing out when assigning the attributes or parsing the rss.
Should be some version dependent thing causing this.
But I'm at a loss here, downgraded feedparser from 6.0.8 to 5.1.2 but it still works for me. No other obvious dependencies involved.

there should be a HA log entry though that explains what goes wrong. It's on the "error" level so maybe you're not catching it. 
Turn error logging please and post me the exception, like

```
logger:
  default: error
```

btw, I'm at:
Home Assistant 2021.12.10 
Python 3.9.2
feedparser 6.0.8

would be helpful to se your configs in order to replicate
/A

**Comment by Kaptensanders** [comment]
Sorry for taking you in the wrong direction. I was still on HA 2021.11 and had not noticed a breaking change in how to populate attributes. Fix is in the skolmat custom component, update with hacs.

please confirm

thanks for reporting
/Anders

**Comment by ctankep23** [comment]
Can confirm update fixes issue. I am looking at the weekly menu. Nice work!

/Seb

**Comment by jsk-sct** [comment]
Yeah. It works for me now too. Both the card and the attributes looks good.
Good job!
