### ISSUE TITLE
great card but more styling options needed

### ISSUE THREAD

**Issue by magune** [Kaptensanders/skolmat-card#2]
This is a great HA card, it works very well!

But I'd like more configuration options for the card, for example set or hide the title, remove the title font setting that doesn't match my dashboard default font selection, etc.

Using mod-card, I think I can override the styling of the heading font. What css tag does it have?

**Comment by magune** [comment]
Additionally, it would be nice if the card could show the upcoming days, and remove the days already past

**Comment by magune** [comment]
I also want to set the card to a fixed height, and it would be great if the contents would be scrollabl (even better if past dates are hidden). Now only the first half of the week is visible, and the past days are not removed, and I cannot scroll down to coming days. Also, I do not want to make the widget higher, as this is the space I have available for this widget
<img width="453" alt="image" src="https://user-images.githubusercontent.com/50596445/168910136-2874bb37-0d98-475c-aaaf-46372e8547ba.png">

**Comment by Kaptensanders** [comment]
thanks, pile on ideas and I'll see what I can do next time I make an effort with the code.

**Comment by magune** [comment]
An additional user request is to remove the School name heading altogether, the card takes a lot of vertical space on my dashboard, and I know what school my kid goes to. I'd rather disable the school name heading altogether and save the vertical space it "wastes"

**Comment by Kaptensanders** [comment]
> This is a great HA card, it works very well!
> 
> But I'd like more configuration options for the card, for example set or hide the title, remove the title font setting that doesn't match my dashboard default font selection, etc.
> 
> Using mod-card, I think I can override the styling of the heading font. What css tag does it have?

Hi, this was added to the 1.2.0 release

**Comment by magune** [comment]
thanks!

**Comment by Kaptensanders** [comment]
> An additional user request is to remove the School name heading altogether, the card takes a lot of vertical space on my dashboard, and I know what school my kid goes to. I'd rather disable the school name heading altogether and save the vertical space it "wastes"

Also added to 1.2.0

**Comment by Kaptensanders** [comment]
Except for the scrollable content I think this was all added, closing for now

**Comment by trendol** [comment]
Hey. About more styling options...
Would love to adjust the font style for the menu/courses. The italic style seems to be hardcoded somewhere and can't really understand where this is set. Yes, I've removed the inline styling in the .js file, but nothing really happens. Ideas?
