### ISSUE TITLE
Update interval?

### ISSUE THREAD

**Issue by newlund** [Kaptensanders/skolmat-card#3]
Hi!

Thanks you for this card! The kids like it :)
However, I can't get it to update every day. I have the menu for current day displayed on a screen attached to the refrigerator. It shows yesterday menu until I refresh the android app.
Any update parameter I have missed?
BR/Nicklas

**Comment by Kaptensanders** [comment]
Hi Nicklas, sounds like my bad. I'll put in a fix.
/Anders

**Comment by Kaptensanders** [comment]
Should be fixed, please verify

**Comment by newlund** [comment]
Thanks! Until now I have used a markdown card but have switched back to your card now.
